name: msv_2224802010188_nguyenquanghung_lab1_3
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '^3.5.0'
dependencies:
  flutter:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/flutter_logo.png
